name: Build and Push Docker Images

on:
  push:
    branches:
      - devops-docker
      - master
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Build backend image
        run: docker build -t "${{ secrets.DOCKER_USERNAME }}/timemanager-backend" ./TimeManagerAPI

      - name: Build frontend image
        run: docker build -t "${{ secrets.DOCKER_USERNAME }}/timemanager-frontend" ./TimeManagerWebInterface/web_interface

      - name: Push backend image
        run: docker push "${{ secrets.DOCKER_USERNAME }}/timemanager-backend"

      - name: Push frontend image
        run: docker push "${{ secrets.DOCKER_USERNAME }}/timemanager-frontend"
 
      - name: Deploy to GCP
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.GCP_SSH_KEY }}

      - name: Update GCP server
        run: |
          ssh -o StrictHostKeyChecking=no \
            ${{ secrets.GCP_USER }}@${{ secrets.GCP_HOST }} \
            "cd ~/timemanager && docker compose pull && docker compose up -d"